
set(bloom_sources
  src/Bloom/Application.h
  src/Bloom/Application/Application.cpp
  src/Bloom/Application/Application.h
  src/Bloom/Application/CoreSystem.h
  src/Bloom/Application/CoreSystemManager.cpp
  src/Bloom/Application/CoreSystemManager.h
  src/Bloom/Application/Input.cpp
  src/Bloom/Application/Input.h
  src/Bloom/Application/InputInternal.h
  src/Bloom/Application/InputEvent.cpp
  src/Bloom/Application/InputEvent.h
  src/Bloom/Application/MessageSystem.cpp
  src/Bloom/Application/MessageSystem.h
  src/Bloom/Application/ResourceUtil.cpp
  src/Bloom/Application/ResourceUtil.h
  src/Bloom/Application/Window.cpp
  src/Bloom/Application/Window.h
  src/Bloom/Application/WindowDelegate.cpp
  src/Bloom/Application/WindowDelegate.h

  src/Bloom/Asset/Asset.cpp
  src/Bloom/Asset/Asset.h
  src/Bloom/Asset/AssetHandle.cpp
  src/Bloom/Asset/AssetHandle.h
  src/Bloom/Asset/Assets.def
  src/Bloom/Asset/AssetManager.cpp
  src/Bloom/Asset/AssetManager.h
  src/Bloom/Asset/Fwd.cpp
  src/Bloom/Asset/Fwd.h
  src/Bloom/Asset/MeshImport.cpp
  src/Bloom/Asset/MeshImport.h
  src/Bloom/Asset/Serialization.h

  src/Bloom/Core.h
  src/Bloom/Core/Autorelease.h
  src/Bloom/Core/Base.h
  src/Bloom/Core/Core.h
  src/Bloom/Core/Debug.cpp
  src/Bloom/Core/Debug.h
  src/Bloom/Core/Dyncast.h
  src/Bloom/Core/EnumCount.h
  src/Bloom/Core/Profile.cpp
  src/Bloom/Core/Profile.h
  src/Bloom/Core/Reference.h
  src/Bloom/Core/Serialize.cpp
  src/Bloom/Core/Serialize.h
  src/Bloom/Core/Time.cpp
  src/Bloom/Core/Time.h
  src/Bloom/Core/Yaml.h

  src/Bloom/GPU.h
  src/Bloom/GPU/BlitContext.h
  src/Bloom/GPU/CommandQueue.h
  src/Bloom/GPU/ComputeContext.h
  src/Bloom/GPU/HardwareDevice.cpp
  src/Bloom/GPU/HardwareDevice.h
  src/Bloom/GPU/HardwarePrimitives.h
  src/Bloom/GPU/HardwareResourceHandle.h
  src/Bloom/GPU/RenderContext.h
  src/Bloom/GPU/Swapchain.h

  src/Bloom/Graphics/Material/Material.cpp
  src/Bloom/Graphics/Material/Material.h
  src/Bloom/Graphics/Material/MaterialInstance.cpp
  src/Bloom/Graphics/Material/MaterialInstance.h
  src/Bloom/Graphics/Material/MaterialParameters.h

  src/Bloom/Graphics/Renderer/BloomFramebuffer.h
  src/Bloom/Graphics/Renderer/BloomRenderer.cpp
  src/Bloom/Graphics/Renderer/BloomRenderer.h
  src/Bloom/Graphics/Renderer/ForwardRenderer.cpp
  src/Bloom/Graphics/Renderer/ForwardRenderer.h
  src/Bloom/Graphics/Renderer/Renderer.cpp
  src/Bloom/Graphics/Renderer/Renderer.h
  src/Bloom/Graphics/Renderer/RendererSanitizer.h
  src/Bloom/Graphics/Renderer/SceneRenderer.cpp
  src/Bloom/Graphics/Renderer/SceneRenderer.h
  src/Bloom/Graphics/Renderer/ShaderParameters.h

  src/Bloom/Graphics/Camera.cpp
  src/Bloom/Graphics/Camera.h
  src/Bloom/Graphics/Lights.cpp
  src/Bloom/Graphics/Lights.h
  src/Bloom/Graphics/MaterialProperties.h
  src/Bloom/Graphics/Mesh.cpp
  src/Bloom/Graphics/Mesh.h
  src/Bloom/Graphics/Renderer.h
  src/Bloom/Graphics/ShaderBase.h
  src/Bloom/Graphics/StaticMesh.cpp
  src/Bloom/Graphics/StaticMesh.h
  src/Bloom/Graphics/Vertex.h

  src/Bloom/Platform/MacOS/Autorelease.mm
  src/Bloom/Platform/MacOS/CocoaWindow.mm
  src/Bloom/Platform/MacOS/ResourceUtil.mm

  src/Bloom/Platform/Metal/MetalBlitContext.h
  src/Bloom/Platform/Metal/MetalBlitContext.mm
  src/Bloom/Platform/Metal/MetalCommandQueue.h
  src/Bloom/Platform/Metal/MetalCommandQueue.mm
  src/Bloom/Platform/Metal/MetalComputeContext.h
  src/Bloom/Platform/Metal/MetalComputeContext.mm
  src/Bloom/Platform/Metal/MetalDevice.h
  src/Bloom/Platform/Metal/MetalDevice.mm
  src/Bloom/Platform/Metal/MetalRenderContext.h
  src/Bloom/Platform/Metal/MetalRenderContext.mm
  src/Bloom/Platform/Metal/MetalSwapchain.h
  src/Bloom/Platform/Metal/MetalSwapchain.mm
  src/Bloom/Platform/Metal/ObjCBridging.h

  src/Bloom/Runtime/CoreRuntime.cpp
  src/Bloom/Runtime/CoreRuntime.h
  src/Bloom/Runtime/SceneSystem.cpp
  src/Bloom/Runtime/SceneSystem.h
  src/Bloom/Runtime/ScriptSystem.cpp
  src/Bloom/Runtime/ScriptSystem.h

  src/Bloom/Scene/Components/AllComponents.h
  src/Bloom/Scene/Components/ComponentBase.h
  src/Bloom/Scene/Components/Hierarchy.h
  src/Bloom/Scene/Components/Lights.h
  src/Bloom/Scene/Components/MeshRenderer.cpp
  src/Bloom/Scene/Components/MeshRenderer.h
  src/Bloom/Scene/Components/Script.cpp
  src/Bloom/Scene/Components/Script.h
  src/Bloom/Scene/Components/Tag.h
  src/Bloom/Scene/Components/Transform.h

  src/Bloom/Scene/Entity.cpp
  src/Bloom/Scene/Entity.h
  src/Bloom/Scene/Scene.cpp
  src/Bloom/Scene/Scene.h
  src/Bloom/Scene/SceneEvents.h
  src/Bloom/Scene/SceneCamera.cpp
  src/Bloom/Scene/SceneCamera.h
)

set(bloom_test_sources
  test/RuntimeSystem.t.cpp
  test/HardwareResourceHandle.t.cpp
)
